## REGRESSION

In [ ]:
## Import the required libraries

import numpy as np
import pandas as pd


In [ ]:
# reading the dataset

df=pd.read_csv('/content/50_Startups.csv')
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [ ]:
df.shape

(108, 5)

In [ ]:
# checking null values

df.isnull().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

In [ ]:
# checking the data type

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108 entries, 0 to 107
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        108 non-null    float64
 1   Administration   108 non-null    float64
 2   Marketing Spend  108 non-null    float64
 3   State            108 non-null    object 
 4   Profit           108 non-null    float64
dtypes: float64(4), object(1)
memory usage: 4.3+ KB


In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
# initializing
le=LabelEncoder()

In [ ]:
df['State'] = le.fit_transform(df['State'])

In [ ]:
df.head()

R&D Spend  Administration  Marketing Spend  State     Profit
0  165349.20       136897.80        471784.10      2  192261.83
1  162597.70       151377.59        443898.53      0  191792.06
2  153441.51       101145.55        407934.54      1  191050.39
3  144372.41       118671.85        383199.62      2  182901.99
4  142107.34        91391.77        366168.42      1  166187.94

In [ ]:
# split the data(independent and dependent)

x= df.iloc[:,:-1].values
y = df.iloc[:,4:5].values

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
# splitting the data(Training & testing)
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size= 0.3,random_state = 0)

In [ ]:
# finding the shape of train and test data

xtrain.shape, xtest.shape

((75, 4), (33, 4))

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
# creating ANN skeleton 

regressor = Sequential()
regressor.add(Dense(4,activation='relu'))
regressor.add(Dense(12,activation='relu'))
regressor.add(Dense(8,activation='relu'))
regressor.add(Dense(9,activation='relu'))
regressor.add(Dense(1,activation='linear'))

In [ ]:
# compiling the ANN model

regressor.compile(optimizer='adam',loss='mse',metrics=['mse'])

In [ ]:
# trainig the model
regressor.fit(xtrain,ytrain,batch_size = 10,epochs=300)


Epoch 1/300
8/8 [==============================] - 1s 5ms/step - loss: 2593909760.0000 - mse: 2593909760.0000
Epoch 2/300
8/8 [==============================] - 0s 3ms/step - loss: 1355116288.0000 - mse: 1355116288.0000
Epoch 3/300
8/8 [==============================] - 0s 3ms/step - loss: 720830336.0000 - mse: 720830336.0000
Epoch 4/300
8/8 [==============================] - 0s 3ms/step - loss: 518905856.0000 - mse: 518905856.0000
Epoch 5/300
8/8 [==============================] - 0s 3ms/step - loss: 480786464.0000 - mse: 480786464.0000
Epoch 6/300
8/8 [==============================] - 0s 2ms/step - loss: 484387456.0000 - mse: 484387456.0000
Epoch 7/300
8/8 [==============================] - 0s 3ms/step - loss: 474720736.0000 - mse: 474720736.0000
Epoch 8/300
8/8 [==============================] - 0s 2ms/step - loss: 466402240.0000 - mse: 466402240.0000
Epoch 9/300
8/8 [==============================] - 0s 2ms/step - loss: 464503808.0000 - mse: 464503808.0000
Epoch 10/300
8/8 [======

In [ ]:
# Testing the model
ypred = regressor.predict(xtest)
ypred

2/2 [==============================] - 0s 5ms/step


array([[ 46384.945],
       [126309.37 ],
       [ 79624.79 ],
       [176824.8  ],
       [ 96830.836],
       [121901.664],
       [127546.76 ],
       [166016.53 ],
       [117416.336],
       [ 50420.047],
       [102344.37 ],
       [119216.32 ],
       [ 46384.945],
       [131364.98 ],
       [ 68627.516],
       [129790.086],
       [129790.086],
       [101951.23 ],
       [ 82280.17 ],
       [141880.12 ],
       [155331.94 ],
       [159162.12 ],
       [108889.766],
       [161836.12 ],
       [ 91457.27 ],
       [173497.64 ],
       [126330.695],
       [ 19669.314],
       [ 86670.55 ],
       [148688.05 ],
       [ 69797.195],
       [202483.84 ],
       [202122.34 ]], dtype=float32)

In [ ]:
from sklearn.metrics import r2_score

In [ ]:
r2_score(ytest,ypred)*100

88.56828130974709

In [ ]:
ypred.flatten()

array([ 46384.945, 126309.37 ,  79624.79 , 176824.8  ,  96830.836,
       121901.664, 127546.76 , 166016.53 , 117416.336,  50420.047,
       102344.37 , 119216.32 ,  46384.945, 131364.98 ,  68627.516,
       129790.086, 129790.086, 101951.23 ,  82280.17 , 141880.12 ,
       155331.94 , 159162.12 , 108889.766, 161836.12 ,  91457.27 ,
       173497.64 , 126330.695,  19669.314,  86670.55 , 148688.05 ,
        69797.195, 202483.84 , 202122.34 ], dtype=float32)

In [ ]:
pd.DataFrame({'Actual_value':ytest.flatten(),'predicted_value':ypred.flatten()}).head(10)

Actual_value  predicted_value
0      64926.08     46384.945312
1     146121.95    126309.367188
2      90708.19     79624.789062
3     191050.39    176824.796875
4     108552.04     96830.835938
5     144259.40    121901.664062
6     124266.90    127546.757812
7     155752.60    166016.531250
8     126992.93    117416.335938
9      42559.73     50420.046875

In [ ]:
# testing the model with random data

regressor.predict([[42576,78124,45789,0]])

1/1 [==============================] - 0s 95ms/step


array([[57353.39]], dtype=float32)

In [ ]:
df.head()

R&D Spend  Administration  Marketing Spend  State     Profit
0  165349.20       136897.80        471784.10      2  192261.83
1  162597.70       151377.59        443898.53      0  191792.06
2  153441.51       101145.55        407934.54      1  191050.39
3  144372.41       118671.85        383199.62      2  182901.99
4  142107.34        91391.77        366168.42      1  166187.94

In [ ]:
regressor.predict([[142107.34,91391.77,366168.42,1]])

1/1 [==============================] - 0s 41ms/step


array([[161836.14]], dtype=float32)