In [1]:
import numpy as np

In [ ]:
## create an array

a= np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [ ]:
a.ndim

1

In [ ]:
## create a two dimensional array

b=np.array([[1,2,3,4],[2,4,5,0]])
b



array([[1, 2, 3, 4],
       [2, 4, 5, 0]])

In [ ]:
b.ndim

2

In [ ]:
## create a three dimensional array

c=np.array([[[1,2,3,4,5],[4,5,6,7,8],[2,3,4,5,6]]])
c

array([[[1, 2, 3, 4, 5],
        [4, 5, 6, 7, 8],
        [2, 3, 4, 5, 6]]])

In [ ]:
c.ndim

3

## Zero's & One's

In [ ]:
var=np.zeros(10)
var

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
var1=np.ones(10)
var1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
## create 3 dimensional array of elements ones with 4rows and 5 columns

q=np.ones((3,4,5))
q

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [ ]:
q.ndim

3

## Functions

In [ ]:
v=np.array([22,56,12,34,77,32])
v

array([22, 56, 12, 34, 77, 32])

In [ ]:
type(v)

numpy.ndarray

In [ ]:
v.argmax()  # max value in index position

4

In [ ]:
v.argmin()   # min value in index position

2

In [ ]:
v[1]

56

In [ ]:
v[1:]

array([56, 12, 34, 77, 32])

In [ ]:
v[1:5]

array([56, 12, 34, 77])

In [ ]:
v[1:-1]

array([56, 12, 34, 77])

In [ ]:
v.dtype

dtype('int64')

In [ ]:
v.size

6

In [ ]:
v[0:-1]


array([22, 56, 12, 34, 77])

In [ ]:
## Create a numpy array with size 5 and the datatype of float

w= np.array([1,2,3,4.4,5])
w

array([1. , 2. , 3. , 4.4, 5. ])

In [ ]:
w.size

5

In [ ]:
w.dtype

dtype('float64')

In [ ]:
# create a two dim array
# four arrays in the external array
# it should have 2 elements each

v = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
v


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
v.ndim

2

## resize & Reshape

In [ ]:
a= np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a.ndim

1

In [ ]:
a.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
a.reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
a.reshape(6,3)

ValueError: ignored

In [ ]:
a.max()

11

In [ ]:
a.min()

0

In [ ]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479])

In [ ]:
np.log(a)

<ipython-input-61-89b6b8e53c58>:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527])

In [ ]:
np.exp(a)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04])

## Transpose

In [2]:
a= np.arange(12)


In [3]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
b=a.reshape(6,2)

In [5]:
b

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [6]:
a1=b.T

In [7]:
a1

array([[ 0,  2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9, 11]])

## Floor & Ceil

In [11]:
arr2=np.array([10.1,3.64,5.2,8.8,7.9,4])
arr2

array([10.1 ,  3.64,  5.2 ,  8.8 ,  7.9 ,  4.  ])

In [12]:
np.floor(arr2)

array([10.,  3.,  5.,  8.,  7.,  4.])

In [13]:
np.ceil(arr2)  # it is giving next integer value

array([11.,  4.,  6.,  9.,  8.,  4.])

In [16]:
r= np.round(arr2)
r

array([10.,  4.,  5.,  9.,  8.,  4.])

## stacking


In [17]:
a1

array([[ 0,  2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9, 11]])

In [21]:
b1=np.arange(14).reshape(2,7)

In [22]:
b1

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13]])

In [23]:
np.hstack((a1,b1))

array([[ 0,  2,  4,  6,  8, 10,  0,  1,  2,  3,  4,  5,  6],
       [ 1,  3,  5,  7,  9, 11,  7,  8,  9, 10, 11, 12, 13]])

In [24]:
c1=np.arange(30).reshape(6,5)
c1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [25]:
d1=np.arange(25).reshape(5,5)
d1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
np.vstack((c1,d1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### For vstack(vertical stack) number of columns should be same and for horizondal(hstack) number of rows should be same for two arrays

## Numpy split

In [27]:
arr23= np.arange(100).reshape(10,10)

In [28]:
arr23

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [29]:
np.vsplit(arr23,2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]),
 array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])]

In [ ]:
# create a numpy array with the shape of 20,10 and divide in to 2 equal parts horizondally

In [33]:
array2=np.arange(200).reshape(20,10)
array2



array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169

In [34]:
np.hsplit(array2,2)

[array([[  0,   1,   2,   3,   4],
        [ 10,  11,  12,  13,  14],
        [ 20,  21,  22,  23,  24],
        [ 30,  31,  32,  33,  34],
        [ 40,  41,  42,  43,  44],
        [ 50,  51,  52,  53,  54],
        [ 60,  61,  62,  63,  64],
        [ 70,  71,  72,  73,  74],
        [ 80,  81,  82,  83,  84],
        [ 90,  91,  92,  93,  94],
        [100, 101, 102, 103, 104],
        [110, 111, 112, 113, 114],
        [120, 121, 122, 123, 124],
        [130, 131, 132, 133, 134],
        [140, 141, 142, 143, 144],
        [150, 151, 152, 153, 154],
        [160, 161, 162, 163, 164],
        [170, 171, 172, 173, 174],
        [180, 181, 182, 183, 184],
        [190, 191, 192, 193, 194]]),
 array([[  5,   6,   7,   8,   9],
        [ 15,  16,  17,  18,  19],
        [ 25,  26,  27,  28,  29],
        [ 35,  36,  37,  38,  39],
        [ 45,  46,  47,  48,  49],
        [ 55,  56,  57,  58,  59],
        [ 65,  66,  67,  68,  69],
        [ 75,  76,  77,  78,  79],
        [ 85,  86,